// Unit tests for canonicalJson — byte-identity with Python's
// json.dumps(value, sort_keys=True).
//
// Every expected literal below was generated by CPython 3.12's
// json.dumps(..., sort_keys=True) (see the H-4 remediation notes) and
// pasted verbatim; the test fails if the JS encoding drifts by even one
// byte. This is the regression net for H-4: the old no-space-separator
// canonicalizer fails these tests.
import { test } from "node:test";
import assert from "node:assert/strict";
import { canonicalJson } from "../src/verify.js";

test("separators use Python's ', ' and ': ' (the H-4 bug)", () => {
  assert.equal(canonicalJson({ a: 1 }), '{"a": 1}');
  assert.equal(canonicalJson([1, 2]), '[1, 2]');
  assert.equal(canonicalJson({ a: [1, { b: 2 }] }), '{"a": [1, {"b": 2}]}');
});

test("nested objects sort keys recursively", () => {
  const v = { b: 1, a: [1, 2.5, "x", null, true, { z: "q", y: 2 }] };
  assert.equal(
    canonicalJson(v),
    '{"a": [1, 2.5, "x", null, true, {"y": 2, "z": "q"}], "b": 1}');
});

test("strings escape exactly like ensure_ascii=True", () => {
  const v = {
    emoji: "🔥",
    accent: "café",
    cjk: "日本語",
    ctrl: "a\nb\tc\x01",
    quote: 'say "hi" \\ bye',
    del: "\x7f",
    lone: "A\ud800B", // lone surrogate, unpaired
  };
  assert.equal(
    canonicalJson(v),
    '{"accent": "caf\\u00e9", "cjk": "\\u65e5\\u672c\\u8a9e", ' +
    '"ctrl": "a\\nb\\tc\\u0001", "del": "\\u007f", ' +
    '"emoji": "\\ud83d\\udd25", "lone": "A\\ud800B", ' +
    '"quote": "say \\"hi\\" \\\\ bye"}');
});

test("keys sort by Unicode code point, not UTF-16 code unit", () => {
  // U+E000 (0xE000) sorts before U+1F600 (0x1F600) by code point, but
  // AFTER it by UTF-16 code unit (0xD83D < 0xE000). Python uses code
  // points; the old Object.keys().sort() did not.
  const v = { b: 1, a: 2, "😀": 3, "": 4, Z: 5, aa: 6 };
  assert.equal(
    canonicalJson(v),
    '{"Z": 5, "a": 2, "aa": 6, "b": 1, "\\ue000": 4, "\\ud83d\\ude00": 3}');
});

test("numbers render like CPython repr", () => {
  const v = {
    int: 42, neg: -17, zero: 0,
    float: 2.5, negfloat: -0.5, negzero: -0.0,
    small: 1e-7, exp1: 1.5e21, tiny: 5e-324,
    fixed1: 0.0001, fixed2: 123456789.123,
  };
  assert.equal(
    canonicalJson(v),
    '{"exp1": 1.5e+21, "fixed1": 0.0001, "fixed2": 123456789.123, ' +
    '"float": 2.5, "int": 42, "neg": -17, "negfloat": -0.5, ' +
    '"negzero": -0.0, "small": 1e-07, "tiny": 5e-324, "zero": 0}');
});

test("non-finite floats match json.dumps allow_nan output", () => {
  assert.equal(canonicalJson(NaN), "NaN");
  assert.equal(canonicalJson(Infinity), "Infinity");
  assert.equal(canonicalJson(-Infinity), "-Infinity");
  assert.equal(canonicalJson({ n: NaN }), '{"n": NaN}');
});

test("booleans, null, empty containers", () => {
  assert.equal(canonicalJson([true, false, null]), "[true, false, null]");
  assert.equal(
    canonicalJson({ empty_obj: {}, empty_arr: [], s: "", n: null }),
    '{"empty_arr": [], "empty_obj": {}, "n": null, "s": ""}');
});

test("unsupported types throw instead of silently mis-encoding", () => {
  assert.throws(() => canonicalJson(undefined), TypeError);
  assert.throws(() => canonicalJson(10n), TypeError);
  assert.throws(() => canonicalJson(() => {}), TypeError);
});

test("documented transport limitation: integral floats read as ints", () => {
  // JSON.parse("1e+16") and JSON.parse("10000000000000000") both yield the
  // same JS number, so the int/float distinction is unrecoverable after
  // parsing. Integer-valued numbers render as Python ints; the receipt
  // schema keeps its only float field (ts) non-integral.
  assert.equal(canonicalJson(1e16), "10000000000000000");
  assert.equal(canonicalJson(1700000000.0), "1700000000");
});
